
server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**, /staffs/**
            #jitne bhi urls ho sare mention karne padenge like above 2

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-94881782.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9jj8vu2QMMCYij5d7
    client-secret: hat-WpmjpYLeBEfF-YEu8EKvsm2tMYoeuQF-1AyL
    scopes: openid, profile, email, offline_access




